baseURL = "https://cjauvin.github.io/"
languageCode = "en-us"
title = "Christian Jauvin"
theme = "PaperMod"

[params]
defaultTheme = "dark"
disableSpecial1stPost = false

[params.homeInfoParams]
Title = ""
Content = "[Professor of Practice](https://www.teluq.ca/siteweb/univ/cjauvin.html) in Computer Science at TELUQ University. My [old blog](https://cjauvin.blogspot.com)."

[[params.socialIcons]]
name = "github"
url = "https://github.com/cjauvin"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.ca/citations?user=AQIwobkAAAAJ&hl=en"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/cjauvin/"

[[params.socialIcons]]
name = "x"
url = "https://x.com/ChristianJauvin"
