baseURL = "https://cjauvin.github.io/"
languageCode = "en-us"
title = "Christian Jauvin"
# theme = "ezhil"
# theme = "hello-friend-ng"
# theme = "dead-simple"
# theme = "archie"
theme = "PaperMod"

[params]
    # mainSections = ["posts"]
    subtitle = ""
    mode = "dark"
    defaultTheme = "dark"
    disableSpecial1stPost = true

# [[params.homeInfoParams]]
#   Title = "Hi there!"
#   Content = "Welcome to my blog"

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/cjauvin"


# [[params.social]]
#     name = "Github"
#     icon = "github"
#     url = "https://github.com/cjauvin"


# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "about/"
#   [[menu.main]]
#     identifier = "posts"
#     name       = "Posts"
#     url        = "posts/"