baseURL = "https://cjauvin.github.io/"
languageCode = "en-us"
title = "Christian Jauvin"
theme = "ezhil"

[params]
    subtitle = ""
    mode = "dark"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/cjauvin"
